### ISSUE TITLE
DIO0 instead of DIO5

### ISSUE THREAD

**Issue by xpix** [raspberrypi/pytrack#8]
I have often noticed this with dave's hardware, I wanted to ask, is it possible to do without the DIO5 output pin of the Lora module with a "normal" LoRa board and to use the DIO0 instead?

I use e.g. the dragino GPS/Lora Board, the DIO5 is not connected to the RPI: http://wiki.dragino.com/images/8/8f/GPS_HAT.sch.png

Here in the code I have seen the following comment: 
https://github.com/raspberrypi/pytrack/blob/master/pytrack/lora.py#L204

Apparently they wanted to use the DIO0, but switched to the DIO5 again. Is there a reason for this?

**Comment by daveake** [comment]
DIO5 is set by the LoRa chip when it has completed a mode change.  As far
as I remember that status cannot be mapped to any other DIO pins.

That said, the mode change activity doesn't take long, and the code that
waits for it to happen could easily be replaced with a short delay.  I'd
need to check what the maximum delay is in the LoRa chip and make sure the
delay is longer than that.

Not sure re that comment vs DIO5 being checked.  I'll take a look.  In my C
code is definitely DIO0 that is used for this function.

**Comment by daveake** [comment]
I've pushed a new version with these changes:

  * Use of DIO5 removed; that pin no longer needs to be connected to the Pi
  * DIO0 is now used to determine when packet has been transmitted
  * DIO0 can now be set from the tracker module as well as directly in
    the lora module

Dave

**Comment by xpix** [comment]
Thanks @daveake, i'll try ur changes and it works as designed.
