### ISSUE TITLE
pytracker freezing?

### ISSUE THREAD

**Issue by xpix** [raspberrypi/pytrack#9]
Hello,

sometimes the pytracker just stopped and didn't send anything anymore, so really only happened once. But if that happens in the air, we have a problem. Is it possible to set up a timeout? If the pytracker does not send out a package in (say 5 minutes), does it restart itself?

cu
Frank

**Comment by daveake** [comment]
It shouldn't stop.  What hardware is this with ?

**Comment by xpix** [comment]
I used this board https://www.electrodragon.com/product/gps-addon-shield-for-raspberry-pi-b2/ with an SX1278 Transceiver and and RPI Zero W.

I'll test this a night and we see it's stopped or not. Maybe also a problem with my wlan ...

**Comment by xpix** [comment]
Ok, after a long 24h test, everythings works as designed.
